### ISSUE TITLE
Running start and buiding for the first time in "dev" does not work.

### ISSUE THREAD

**Issue by patomation** [patomation/twitch-bot#18]
You have to re-run because concurrently runs everything at the same time and watches....
Is there  pre-start npm hook that we can run that will build things first?

**Comment by patomation** [comment]
Maybe better documentation on this. But it kinda sucks when it breaks after I delete the build folder and start again...

**Comment by creativenull** [comment]
Hey!

I won't mind looking into this, I've done something like this with one of my projects. But I will need help as to how I can go about writing this without breaking changes 🙂

Method 1: It's the way how you described it, using a `prestart` command script. We can just run `npm start` and it will run the `prestart` command before and then the `start` command.

Method 2: The other way I was thinking was to utilize typescript watchers that come with `nodemon` and `webpack` and just let them watch `.ts` files instead of their compiled `.js` files. So, less watchers to run (2 vs 4 watchers) and no changes to `start` script, but when ready to deploy to production is where we can add a `build` or a `prod` script that will compile the files ready for deployment.

Let me know what you think. I already tried out the first method and it seems to work with no issue. I don't have the OAuth setup though, will I need that as well?

**Comment by patomation** [comment]
Hey there, I like the direction you are going. You could try option 2 to see if you can get it to work with a fresh build and dev mode would work. The js files need to be watched so webpack and nodemon can run them after typescript compiles them. So if you can get that working that would be great. Nice job getting option 1 working. As a fallback that would be acceptable as well.

As for needing OAuth. you might want to get that set up if you want to test the chat bot. But it should/may run without it.

Thank you.

**Comment by creativenull** [comment]
Alright! I'll get started on that. Quick question, are you deploying the overlay to a server or is this just to run within your local machine? I'm assuming bot can be deployed to a remote server or just local?

**Comment by patomation** [comment]
I run it on my local machine, but I will probably look into deploying it on a server somewhere eventually. I would need to find an always running node server.

**Comment by creativenull** [comment]
So I am able to get method 2 working. PR incoming for your review.

There was an issue with typescript not picking up `badwords` package properly which I have a fix for but I think that's not relevant to this issue (maybe a new issue?).

**Comment by patomation** [comment]
fixed with #46
